# Auto-generated by github.com/dannotes/onair release workflow.
# Do not edit by hand — your changes will be overwritten on the next release.
class Onair < Formula
  desc "Watch Microsoft Teams and turn a Philips WiZ smart bulb red while on a call"
  homepage "https://github.com/dannotes/onair"
  version "0.1.6"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/dannotes/onair/releases/download/v0.1.6/onair-aarch64-apple-darwin.tar.gz"
      sha256 "7364de09399d889c3a2b4e29ff9bda996a9839e7cd5549808b10afdde03f8e86"
    end
    on_intel do
      url "https://github.com/dannotes/onair/releases/download/v0.1.6/onair-x86_64-apple-darwin.tar.gz"
      sha256 "56ce23cc1ac3a27e835ae11cc9ad4b347dfdee5c602d3190abf5f8c68b5977d8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dannotes/onair/releases/download/v0.1.6/onair-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "6a503cb9dbdaf7b7428b90e3a35b8729e8723ac9e0a6f1c607b2321b095e84e2"
    end
  end

  def install
    bin.install "onair"
    doc.install "README.md", "LICENSE"
  end

  def caveats
    <<~CAVEAT
      Run onair to launch the dashboard:
          onair

      The dashboard at http://localhost:9876 will open in your browser
      automatically the first time. Configure your bulb there, then
      toggle "Run on Login" in Settings → Advanced if you want it to
      start on every login.

      Config and call history live at:
          ~/Library/Application Support/Onair/onair.db
    CAVEAT
  end

  test do
    assert_match "onair #{version}", shell_output("#{bin}/onair --version")
  end
end
