# Auto-generated by github.com/dannotes/onair release workflow.
# Do not edit by hand — your changes will be overwritten on the next release.
class Onair < Formula
  desc "Watch Microsoft Teams and turn a Philips WiZ smart bulb red while on a call"
  homepage "https://github.com/dannotes/onair"
  version "0.1.5"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/dannotes/onair/releases/download/v0.1.5/onair-aarch64-apple-darwin.tar.gz"
      sha256 "664862c4336a7783a46516b0cebf372469e33ecc6b9252a0ebb1d6553cbf69fd"
    end
    on_intel do
      url "https://github.com/dannotes/onair/releases/download/v0.1.5/onair-x86_64-apple-darwin.tar.gz"
      sha256 "e2d9eafc6682f478687489819fd88061b1ae1771a21d5cc8417990d689de0e49"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dannotes/onair/releases/download/v0.1.5/onair-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "090c4a35aa52876ac6b2488114451207b348d22b92b9d680021699c351ce43a2"
    end
  end

  def install
    bin.install "onair"
    doc.install "README.md", "LICENSE"
  end

  def caveats
    <<~CAVEAT
      Run onair to launch the dashboard:
          onair

      The dashboard at http://localhost:9876 will open in your browser
      automatically the first time. Configure your bulb there, then
      toggle "Run on Login" in Settings → Advanced if you want it to
      start on every login.

      Config and call history live at:
          ~/Library/Application Support/Onair/onair.db
    CAVEAT
  end

  test do
    assert_match "onair #{version}", shell_output("#{bin}/onair --version")
  end
end
